### ISSUE TITLE
橫軸刻度說明

### ISSUE THREAD

**Issue by audreyt** [g0v/npratio#1]
0 ~ 11 的刻度，如果換成中文月份（一月到十二月）也許比較容易瞭解？

**Comment by ben196888** [comment]
這個我正在修（在demo的時候已經發現，可是沒修好）

**Comment by ben196888** [comment]
我改成另一種方式呈現，希望這樣看起來也會比較舒服。
commit: 079896d6f11693851c8474aac8c206c8baad096a
